### ISSUE TITLE
Skipping a page from a tile/plugin

### ISSUE THREAD

**Issue by quintenstar** [info-beamer/package-scheduled-player#4]
I don't think it's possible yet, but it would be awesome if it were possible to be able to tell the scheduler to skip a page/slide from a child tile/plugin.

It would be nice for cases when there is no dynamic content available to be shown by the plugin. And not having to display fallback assets as an alternative.

**Comment by dividuum** [comment]
This is actually possible already: If the tile exports a `can_show` function and that function returns `false`, the whole page will be skipped during each scheduling round. See https://github.com/info-beamer/package-scheduled-player/blob/f124700941125df7f6a1801e8de15b397434b1d9/frab/tile.lua#L570-L581
